### PR TITLE
initial commit - added logger from GRO/BRP, initial setup, added init…

### PR DESCRIPTION
**Pull request by joefitter**
… test

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @gxxm @bendiggle mind having a look? Also @JoeChapman could you please give me admin access to this repo? Or enable it on Travis as I cant. Ta

**Comment by JoeChapman** [comment]
LGTM, @easternbloc

**Comment by easternbloc** [comment]
Maybe I'm being dumb but I'm struggling to see what the use case for this is?

**Comment by easternbloc** [comment]
It's just creating a winston instance...?

**Comment by joefitter** [comment]
with some settings yeah, pretty much - but we currently carry round a /lib/logger.js which does exactly that, in every app

**Comment by easternbloc** [comment]
hmm, OK I see what the intention is. I'm not sure if we should be calling hof-logger something just doesn't feel right about that as it's not doing anything specific. What do other people think? @danielepolencic

**Comment by danielepolencic** [comment]
image

**Comment by danielepolencic** [comment]
One can always decide not to use this library.

If this is useful for GRO/BRP, I don't see why we shouldn't create the repo. Even if this is just common config, perhaps there's value in having a standard way of logging.

On a side note, RT and EVW are using a very similar strategy: https://gitlab.digital.homeoffice.gov.uk/REGT/rtp-logger

As for the name, I have mixed feelings. @easternbloc is right, this is just a glorified wrapper of winston. However, the prefix HOF suggests this is officially supported by the HOF team.
I think we want to encourage teams to use certain modules. Perhaps this sounds like a good opportunity to do so (i.e. I use HOF then I should use HOF logger)?

We get consistent logging across projects as a benefit. Not bad at all, if you ask me.

**Comment by easternbloc** [comment]
> If this is useful for GRO/BRP, I don't see why we shouldn't create the repo. Even if this is just common config, perhaps there's value in having a standard way of logging.

More than happy with that I just wasn't sure about the name. I guess if we look at it from the view point that it's supported by the HOF team then fine. I'm OK with this.

**Pull request merged**
